print("comparators 1")
print(1<2)
print(1<=2)
print(1>2)
print(1>=2)

print("comparators 2")
print(5<3)
print(5<=3)
print(5>3)
print(5>=3)

print("comparators 3")
print(5<5)
print(5<=5)
print(5>5)
print(5>=5)

print("equality 1 ints")
print(5==5)
print(5!=5)
print(5==10)
print(5!=10)

print("equality 2 ints/bools")
print(1==True)
print(1!=True)
print(".")
print(0==True)
print(0!=True)
print(".")
print(1==False)
print(1!=False)
print(".")
print(0==False)
print(0!=False)

print("prints, str add, int binops")
print(7+3)
print(True)
print("chacal" + " guillaume" + " ahahahhah xd !!!!")
print(7-3)
print(True)
print(7*3)
print(48481515)
print(True)
print(7//3)
print(True)
print(None)
print("a")
print("b")
print("c")
print(None)
print("d")
print(7%3)
print("walla c'est fini! ù*^$%µ£¨µ£%µè_(éç là oui je le jure")
