print(7+3)
print(True)
print("chacal")
print(7-3)
print(True)
print(7*3)
print(48481515)
print(True)
print(7//3)
print(True)
print(None)
print("a")
print("b")
print("c")
print(None)
print("d")
print(7%3)
print("walla c'est fini! ù*^$%µ£¨µ£%µè_(éç là oui je le jure")
